version: "3.8"
services: 
    db:
        image: mysql
        container_name: db
        restart: always
        ports: 
            - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - "wp-db:/var/lib/mysql:rw"
        networks: 
            - database
    # back:
    #     build: "."
    #     container_name: "back_end"
    #     volumes: 
    #         - ./.env:/root/.env
    #     ports: 
    #         - 8080:8080
    #     networks: 
    #         - database
    #         - dev-network
    #     restart: always
    message_broker:
        image: rabbitmq:3-management-alpine
        container_name: message_broker
        ports:
            - 5672:5672   # for sender and consumer connections
            - 15672:15672 # for serve RabbitMQ GUI
        volumes:
            - ./dev-rabbitmq/data/:/var/lib/rabbitmq
            - ./dev-rabbitmq/log/:/var/log/rabbitmq
        environment: 
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        restart: always
        networks:
            - dev-network


volumes: 
    wp-db: {}
networks: 
    database:
        driver: "bridge"
    dev-network:
        driver: "bridge"